"use client";

import { useState, type ReactNode } from "react";
import {
  Bell,
  Mail,
  MessageSquare,
  Pin,
  Send,
  Share2,
  Slack,
  Sparkles,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

export type ActionKind =
  | "slack"
  | "email"
  | "im"
  | "pin"
  | "reminder"
  | "share";

export interface WorkbenchAction {
  kind: ActionKind;
  label: string;
  /** When true, the card is styled as a chat-driven (contextual) action */
  contextual?: boolean;
  /** Optional pre-filled recipient (e.g., "CFO", "Sales Lead") */
  recipient?: string;
  /** Optional pre-filled message body */
  body?: string;
}

interface WorkbenchActionStripProps {
  /** Contextual actions generated by chat response */
  contextualActions?: WorkbenchAction[];
  /** Static page title for pin/reminder defaults */
  contextTitle?: string;
  className?: string;
}

const KIND_META: Record<ActionKind, { icon: typeof Slack; accent: string; title: string }> = {
  slack: { icon: Slack, accent: "text-[#4A154B]", title: "Send Slack message" },
  email: { icon: Mail, accent: "text-blue-600", title: "Send email" },
  im: { icon: MessageSquare, accent: "text-emerald-600", title: "Send direct message" },
  pin: { icon: Pin, accent: "text-amber-600", title: "Pin to workspace" },
  reminder: { icon: Bell, accent: "text-violet-600", title: "Set reminder" },
  share: { icon: Share2, accent: "text-slate-600", title: "Share" },
};

const QUICK_ACTIONS: WorkbenchAction[] = [
  { kind: "slack", label: "Slack teammate" },
  { kind: "email", label: "Email" },
  { kind: "im", label: "IM" },
  { kind: "pin", label: "Pin" },
  { kind: "reminder", label: "Remind me" },
  { kind: "share", label: "Share copy" },
];

export function WorkbenchActionStrip({
  contextualActions = [],
  contextTitle,
  className,
}: WorkbenchActionStripProps) {
  const [openAction, setOpenAction] = useState<WorkbenchAction | null>(null);

  const handleAction = (action: WorkbenchAction) => {
    setOpenAction(action);
  };

  return (
    <>
      <div
        className={cn(
          "flex items-center gap-2 border-t border-slate-200 bg-white px-4 py-2 overflow-x-auto",
          className
        )}
      >
        <div className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wide text-slate-500 shrink-0">
          <Sparkles className="h-3 w-3 text-primary" />
          Next best action
        </div>
        <div className="h-4 w-px bg-slate-200 shrink-0" />

        {/* Contextual action cards (from chat) */}
        {contextualActions.map((a, i) => {
          const meta = KIND_META[a.kind];
          const Icon = meta.icon;
          return (
            <button
              key={`ctx-${i}`}
              onClick={() => handleAction(a)}
              className="inline-flex items-center gap-1.5 rounded-md border border-primary/30 bg-primary/5 px-2.5 py-1 text-xs font-medium text-primary hover:bg-primary/10 transition-colors shrink-0"
              title={meta.title}
            >
              <Icon className="h-3.5 w-3.5" />
              <span>{a.label}</span>
              {a.recipient && (
                <span className="text-[10px] text-primary/70">· {a.recipient}</span>
              )}
            </button>
          );
        })}

        {contextualActions.length > 0 && (
          <div className="h-4 w-px bg-slate-200 shrink-0" />
        )}

        {/* Quick actions */}
        {QUICK_ACTIONS.map((a) => {
          const meta = KIND_META[a.kind];
          const Icon = meta.icon;
          return (
            <button
              key={a.kind}
              onClick={() => handleAction(a)}
              className="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-2.5 py-1 text-xs font-medium text-slate-600 hover:bg-slate-50 hover:text-slate-900 transition-colors shrink-0"
              title={meta.title}
            >
              <Icon className={cn("h-3.5 w-3.5", meta.accent)} />
              <span>{a.label}</span>
            </button>
          );
        })}
      </div>

      <ActionSheet
        action={openAction}
        contextTitle={contextTitle}
        onClose={() => setOpenAction(null)}
      />
    </>
  );
}

/* ─── Inline action sheet (nothing leaves the app) ─── */

interface ActionSheetProps {
  action: WorkbenchAction | null;
  contextTitle?: string;
  onClose: () => void;
}

function ActionSheet({ action, contextTitle, onClose }: ActionSheetProps) {
  const [recipient, setRecipient] = useState("");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [when, setWhen] = useState("");

  // Reset/prefill on open
  const open = action !== null;
  const meta = action ? KIND_META[action.kind] : null;

  const handleOpenChange = (next: boolean) => {
    if (!next) {
      setRecipient("");
      setSubject("");
      setBody("");
      setWhen("");
      onClose();
    }
  };

  const handleSubmit = () => {
    if (!action) return;
    const label =
      {
        slack: `Slack sent to ${recipient || "teammate"}`,
        email: `Email sent to ${recipient || "recipient"}`,
        im: `Message sent to ${recipient || "teammate"}`,
        pin: `Pinned "${subject || contextTitle || "view"}" to your workspace`,
        reminder: `Reminder set for ${when || "later"}`,
        share: `Copy shared with ${recipient || "recipient"}`,
      }[action.kind] ?? "Action complete";
    toast.success(label);
    handleOpenChange(false);
  };

  return (
    <Sheet open={open} onOpenChange={handleOpenChange}>
      <SheetContent side="right" className="w-[380px] sm:w-[420px] p-0">
        <div className="flex h-full flex-col">
          <SheetHeader className="border-b border-slate-200 px-4 py-3">
            <SheetTitle className="flex items-center gap-2 text-sm font-semibold">
              {meta && <meta.icon className={cn("h-4 w-4", meta.accent)} />}
              {meta?.title ?? "Action"}
            </SheetTitle>
          </SheetHeader>

          <div className="flex-1 overflow-y-auto p-4 space-y-3">
            {action && <ActionFields
              action={action}
              contextTitle={contextTitle}
              recipient={recipient}
              setRecipient={setRecipient}
              subject={subject}
              setSubject={setSubject}
              body={body}
              setBody={setBody}
              when={when}
              setWhen={setWhen}
            />}
          </div>

          <div className="shrink-0 border-t border-slate-200 p-3 flex items-center justify-end gap-2">
            <Button variant="outline" size="sm" onClick={() => handleOpenChange(false)}>
              <X className="h-3.5 w-3.5 mr-1" /> Cancel
            </Button>
            <Button size="sm" onClick={handleSubmit}>
              <Send className="h-3.5 w-3.5 mr-1" /> Send
            </Button>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}

interface ActionFieldsProps {
  action: WorkbenchAction;
  contextTitle?: string;
  recipient: string;
  setRecipient: (v: string) => void;
  subject: string;
  setSubject: (v: string) => void;
  body: string;
  setBody: (v: string) => void;
  when: string;
  setWhen: (v: string) => void;
}

function ActionFields({
  action,
  contextTitle,
  recipient,
  setRecipient,
  subject,
  setSubject,
  body,
  setBody,
  when,
  setWhen,
}: ActionFieldsProps) {
  const defaultBody =
    action.body ??
    (contextTitle ? `Sharing context on ${contextTitle}.` : "");

  const recipientField = (
    <Field label="To">
      <Input
        value={recipient}
        onChange={(e) => setRecipient(e.target.value)}
        placeholder={action.recipient ?? "Search teammates"}
      />
    </Field>
  );

  const bodyField = (
    <Field label="Message">
      <Textarea
        value={body || defaultBody}
        onChange={(e) => setBody(e.target.value)}
        rows={6}
        className="resize-none"
      />
    </Field>
  );

  switch (action.kind) {
    case "slack":
    case "im":
      return (
        <>
          {recipientField}
          {bodyField}
        </>
      );
    case "email":
      return (
        <>
          {recipientField}
          <Field label="Subject">
            <Input
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder={contextTitle ?? "Subject"}
            />
          </Field>
          {bodyField}
        </>
      );
    case "pin":
      return (
        <>
          <Field label="Label">
            <Input
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder={contextTitle ?? "Pin label"}
            />
          </Field>
          <Field label="Note (optional)">
            <Textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={3}
              className="resize-none"
              placeholder="Why this matters..."
            />
          </Field>
        </>
      );
    case "reminder":
      return (
        <>
          <Field label="What">
            <Input
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder={contextTitle ?? "Remind me to..."}
            />
          </Field>
          <Field label="When">
            <Input
              value={when}
              onChange={(e) => setWhen(e.target.value)}
              placeholder="e.g. tomorrow 9am"
            />
          </Field>
        </>
      );
    case "share":
      return (
        <>
          {recipientField}
          <Field label="Note">
            <Textarea
              value={body || defaultBody}
              onChange={(e) => setBody(e.target.value)}
              rows={4}
              className="resize-none"
            />
          </Field>
        </>
      );
    default:
      return null;
  }
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="space-y-1.5">
      <Label className="text-xs font-medium text-slate-600">{label}</Label>
      {children}
    </div>
  );
}
