/**
 * @module workspace
 * @description Type definitions for Meeru AI workspace entities including
 * pinned metrics, watchlist items, activity events, and data templates.
 */

/**
 * A pinned metric displayed on the workspace dashboard.
 * Pins allow users to track key values from any module at a glance.
 */
export interface Pin {
  /** Unique identifier for the pin */
  id: string;
  /** Human-readable label displayed on the dashboard */
  label: string;
  /** Current value of the pinned metric */
  value: string | number;
  /** Display format for rendering the value */
  format: "currency" | "number" | "percentage" | "text";
  /** Direction of the trend compared to the previous period */
  trend?: "up" | "down" | "flat";
  /** Formatted string describing the trend magnitude (e.g. "+12%") */
  trendValue?: string;
  /** Data source identifier the pin reads from */
  source: string;
  /** Module this pin belongs to */
  module: string;
  /** Auto-refresh interval in seconds; undefined means manual refresh only */
  refreshInterval?: number;
  /** ISO-8601 timestamp of the last data refresh */
  lastRefreshed: string;
  /** ISO-8601 timestamp when the pin was created */
  createdAt: string;
  /** Display order on the dashboard (lower numbers appear first) */
  order: number;
}

/**
 * An item on the user's watchlist that is monitored against optional thresholds.
 * When a threshold is breached the status transitions to Warning or Alert.
 */
export interface WatchlistItem {
  /** Unique identifier for the watchlist item */
  id: string;
  /** Human-readable label */
  label: string;
  /** Short description of what is being watched */
  description: string;
  /** Module this item belongs to */
  module: string;
  /** Type of the entity being watched (e.g. "case", "payment") */
  entityType: string;
  /** Identifier of the specific entity being watched */
  entityId: string;
  /** Current value of the monitored metric */
  currentValue: string | number;
  /** Numeric threshold that triggers a status change */
  threshold?: number;
  /** Whether the alert fires when the value goes above or below the threshold */
  thresholdDirection?: "above" | "below";
  /** Current monitoring status */
  status: "Normal" | "Warning" | "Alert";
  /** ISO-8601 timestamp of the last threshold check */
  lastChecked: string;
  /** ISO-8601 timestamp when the watchlist item was created */
  createdAt: string;
}

/**
 * A single activity event recorded in the workspace activity feed.
 * Events are generated by user actions, system processes, and automated workflows.
 */
export interface ActivityEvent {
  /** Unique identifier for the event */
  id: string;
  /** Categorised event type */
  type:
    | "case_created"
    | "case_updated"
    | "rule_triggered"
    | "export_completed"
    | "user_action"
    | "system_event"
    | "match_completed"
    | "task_completed";
  /** Short title summarising the event */
  title: string;
  /** Detailed description of what occurred */
  description: string;
  /** Module where the event originated */
  module: string;
  /** Optional identifier of the related entity */
  entityId?: string;
  /** Name or identifier of the user or system that triggered the event */
  actor: string;
  /** ISO-8601 timestamp when the event occurred */
  timestamp: string;
  /** Arbitrary key-value metadata attached to the event */
  metadata?: Record<string, string | number>;
}

/**
 * A reusable data template that defines column layout, default filters,
 * and sort configuration for tabular views within a module.
 */
export interface DataTemplate {
  /** Unique identifier for the template */
  id: string;
  /** Human-readable template name */
  name: string;
  /** Description of the template's purpose */
  description: string;
  /** Module this template applies to */
  module: string;
  /** Ordered list of column definitions */
  columns: Array<{
    /** Column field key used for data binding */
    key: string;
    /** Display label for the column header */
    label: string;
    /** Data type used for formatting and sorting */
    type: "text" | "number" | "date" | "currency";
  }>;
  /** Default filter key-value pairs applied when the template is loaded */
  filters?: Record<string, string>;
  /** Default column key to sort by */
  sortBy?: string;
  /** Default sort direction */
  sortOrder?: "asc" | "desc";
  /** Identifier of the user who created the template */
  createdBy: string;
  /** ISO-8601 timestamp when the template was created */
  createdAt: string;
  /** ISO-8601 timestamp when the template was last updated */
  updatedAt: string;
}
